

from enum import Enum


class DIRECTION(Enum):
    NONE = 0
    FORWARD = 1
    BACKWARD = 2
    LEFT = 3
    RIGHT = 4
    UP = 5
    DOWN = 6


class AERIALTAKEOFF(Enum):
    NONE = 0
    QUICK = 1
    QUICK_SINGLE = 2
    SINGLE = 3
    DOUBLE = 4
    FALL = 5


class KICKOFFTYPE(Enum):
    NONE = 0
    OFF_CENTER = 1
    DIAGONAL = 2
    STRAIGHT = 3


OCTANE_LENGTH = 82.5
BALL_RADIUS = 92.75
BOOST_CONSUMPTION_RATE = 33.3
INV_BOOST_CONSUMPTION_RATE = 1 / BOOST_CONSUMPTION_RATE
BOOST_ACCELERATION = 1066
CAR_BRAKING = 3500
ZERO_THROTTLE = 525
MAX_CAR_VEL = 2300
INV_MAX_CAR_VEL = 1 / MAX_CAR_VEL
TOP_DRIVE_VEL = 1410
